services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env
    networks:
      - frontend-network
    restart: unless-stopped
networks:
  frontend-network:
    driver: bridge
