version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - ${PORT_POSTGRES}
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
    name: matias-inventory-network
