version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - ${PORT_POSTGRES}
    environment:
      - DATABASE_HOST= ${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PORT_PGADMIN}
    depends_on:
      - postgres